In [1]:
import numpy as np

# Nd-Array

In [6]:
arr = np.array( [1, 2, 3] )
arr2 = np.array( [ [1, 2, 3],
                   [4, 5, 5] ])
print(arr2)

[[1 2 3]
 [4 5 5]]


# LIST VS NUMPY

In [2]:
import time
 
size = 10000000

list1 = range(size)
list2 = range(size)
array1 = np.arange(size)
array2 = np.arange(size)
 
initialTime = time.time()

sm = 0
for i in range(size):
    sm +=  list1[i] + list2[i]
 
print("LIST : ", (time.time() - initialTime), "seconds")
 
initialTime = time.time()
 
resultantArray = array1 * array2
 
print("NP ARRAY : ", (time.time() - initialTime), "seconds")

LIST :  1.5642669200897217 seconds
NP ARRAY :  0.026340007781982422 seconds


# Methods

In [10]:
print(arr2.dtype)
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
# np.nan
# np.inf

int64
(2, 3)
2
6


# TO CREATE NP ARRAY

In [11]:
print(np.full((2,3), 5))
print(np.ones((5,3)))
print(np.arange(2,10))
print(np.linspace(1, 20, 5))

print(np.random.randint(2, 100, (2,4)))
print(np.random.binomial(3, 0.2, (3,5)))
print(np.random.choice( [10, 4,3], (3,5) ))

[[5 5 5]
 [5 5 5]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[2 3 4 5 6 7 8 9]
[ 1.    5.75 10.5  15.25 20.  ]
[[28 14 17 49]
 [96 74 84 30]]
[[1 0 0 2 1]
 [1 0 0 0 0]
 [0 0 0 2 1]]
[[ 4  3 10  4  4]
 [10  4 10  4 10]
 [ 4 10 10  4  3]]


# MANIPULATION

In [ ]:
newArr = np.array( [[25, 10,  9,  5, 21, 3],
                    [16, 13,  3, 23, 17, 8]] ) 
newArr2 = np.array( [[25, 10,  9,  5, 21, 3],
                    [16, 13,  3, 23, 17, 8]] ) 
# print(newArr.reshape( (4,3) ))
# print(newArr.flatten())
# print(newArr.transpose())
newArr = np.append(newArr, newArr2, axis=1 )
newArr

# VECTOR LIKE BEHAVIOUR

In [12]:
lst1 = [5, 3]
lst2 = [3, 7]
ar = np.array([5,3])
ar2 = np.array([3,7])
print(lst1 + lst2)
print(ar * ar2)

print(np.dot(ar, ar2))

[5, 3, 3, 7]
[15 21]
36


# AGGREGATES

In [ ]:
print(newArr.min())
print(newArr.max())
print(newArr.mean())
print(np.median(newArr))
print(newArr.sum())
print(newArr.std())

# --------------------